### ISSUE TITLE
simulation.db

### ISSUE THREAD

**Issue by LCC9125** [YSocialTwin/YClient#4]
Hi, why is there no content in my simulation.db after I followed the steps in the README? Is this because there is no relevant code stored in client_base?

**Comment by GiulioRossetti** [comment]
The execution results are stored in the YServer, not in the YClient.
The simulation.db in YClient is used to locally load the websites and articles collected using the RSS feeds (you need to specify the --news and --feeds flags - respectively to populate the news db and to specify the rss feed json file - to load them)
